name: Status check on pull request

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12
        env:
          CI: true
      - name: Install Dependencies
        run: yarn
      - run: yarn test
      - run: yarn build
